--! 1. Cards (The Parents)

--* Common Cards (29 entries)
INSERT INTO Card (card_id, name, elixir_cost, rarity, type) VALUES 
(1, 'Skeletons', 1, 'Common', 'Troop'),
(2, 'Fire Spirit', 1, 'Common', 'Troop'),
(3, 'Electro Spirit', 1, 'Common', 'Troop'),
(4, 'Ice Spirit', 1, 'Common', 'Troop'),
(5, 'Goblins', 2, 'Common', 'Troop'),
(6, 'Spear Goblins', 2, 'Common', 'Troop'),
(7, 'Bomber', 2, 'Common', 'Troop'),
(8, 'Bats', 2, 'Common', 'Troop'),
(9, 'Berserker', 2, 'Common', 'Troop'),
(10, 'Snowball', 2, 'Common', 'Spell'),
(11, 'Zap', 2, 'Common', 'Spell'),
(12, 'Knight', 3, 'Common', 'Troop'),
(13, 'Archers', 3, 'Common', 'Troop'),
(14, 'Minions', 3, 'Common', 'Troop'),
(15, 'Arrows', 3, 'Common', 'Spell'),
(16, 'Cannon', 3, 'Common', 'Building'),
(17, 'Goblin Gang', 3, 'Common', 'Troop'),
(18, 'Skeleton Barrel', 3, 'Common', 'Troop'),
(19, 'Firecracker', 3, 'Common', 'Troop'),
(20, 'Royal Delivery', 3, 'Common', 'Spell'),
(21, 'Skeleton Dragons', 4, 'Common', 'Troop'),
(22, 'Mortar', 4, 'Common', 'Building'),
(23, 'Tesla', 4, 'Common', 'Building'),
(24, 'Barbarians', 5, 'Common', 'Troop'),
(25, 'Minion Horde', 5, 'Common', 'Troop'),
(26, 'Rascals', 5, 'Common', 'Troop'),
(27, 'Royal Giant', 6, 'Common', 'Troop'),
(28, 'Elite Barbarians', 6, 'Common', 'Troop'),
(29, 'Royal Recruits', 7, 'Common', 'Troop')
ON CONFLICT (name) DO NOTHING;

--* Rare Cards (30 entries)
INSERT INTO Card (card_id, name, elixir_cost, rarity, type) VALUES
(30, 'Heal Spirit', 1, 'Rare', 'Troop'),
(31, 'Ice Golem', 2, 'Rare', 'Troop'),
(32, 'Suspicious Bush', 2, 'Rare', 'Troop'),
(33, 'Tombstone', 3, 'Rare', 'Building'),
(34, 'Dart Goblin', 3, 'Rare', 'Troop'),
(35, 'Earthquake', 3, 'Rare', 'Spell'),
(36, 'Elixir Golem', 3, 'Rare', 'Troop'),
(37, 'Mega Minion', 3, 'Rare', 'Troop'),
(38, 'Musqueteer', 4, 'Rare', 'Troop'),
(39, 'Mini PEKKA', 4, 'Rare', 'Troop'),
(40, 'Goblin Hut', 4, 'Rare', 'Building'),
(41, 'Goblin Cage', 4, 'Rare', 'Building'),
(42, 'Fireball', 4, 'Rare', 'Spell'),
(43, 'Valkyrie', 4, 'Rare', 'Troop'),
(44, 'Battle Ram', 4, 'Rare', 'Troop'),
(45, 'Bomb Tower', 4, 'Rare', 'Building'),
(46, 'Hog Rider', 4, 'Rare', 'Troop'),
(47, 'Flying Machine', 4, 'Rare', 'Troop'),
(48, 'Battle Healer', 4, 'Rare', 'Troop'),
(49, 'Zappies', 4, 'Rare', 'Troop'),
(50, 'Furnace', 4, 'Rare', 'Troop'),
(51, 'Goblin Demolisher', 4, 'Rare', 'Troop'),
(52, 'Giant', 5, 'Rare', 'Troop'),
(53, 'Wizard', 5, 'Rare', 'Troop'),
(54, 'Inferno Tower', 5, 'Rare', 'Building'),
(55, 'Royal Hogs', 5, 'Rare', 'Troop'),
(56, 'Rocket', 6, 'Rare', 'Spell'),
(57, 'Barbarian Hut', 6, 'Rare', 'Building'),
(58, 'Elixir Collector', 6, 'Rare', 'Building'),
(59, 'Three Musketeers', 9, 'Rare', 'Troop')
ON CONFLICT (name) DO NOTHING;

--* Epic Cards (33 entries)
INSERT INTO Card (card_id, name, elixir_cost, rarity, type) VALUES
(60, 'Mirror', 1, 'Epic', 'Spell'),
(61, 'Barbarian Barrel', 2, 'Epic', 'Spell'),
(62, 'Wall Breakers', 2, 'Epic', 'Troop'),
(63, 'Goblin Curse', 2, 'Epic', 'Spell'),
(64, 'Rage', 2, 'Epic', 'Spell'),
(65, 'Skeleton Army', 3, 'Epic', 'Troop'),
(66, 'Guards', 3, 'Epic', 'Troop'),
(67, 'Goblin Barrel', 3, 'Epic', 'Spell'),
(68, 'Vines', 3, 'Epic', 'Spell'),
(69, 'Tornado', 3, 'Epic', 'Spell'),
(70, 'Clone', 3, 'Epic', 'Spell'),
(71, 'Void', 3, 'Epic', 'Spell'),
(72, 'Baby Dragon', 4, 'Epic', 'Troop'),
(73, 'Dark Prince', 4, 'Epic', 'Troop'),
(74, 'Freeze', 4, 'Epic', 'Spell'),
(75, 'Rune Giant', 4, 'Epic', 'Troop'),
(76, 'Poison', 4, 'Epic', 'Spell'),
(77, 'Hunter', 4, 'Epic', 'Troop'),
(78, 'Goblin Drill', 4, 'Epic', 'Building'),
(79, 'Witch', 5, 'Epic', 'Troop'),
(80, 'Balloon', 5, 'Epic', 'Troop'),
(81, 'Prince', 5, 'Epic', 'Troop'),
(82, 'Electro Dragon', 5, 'Epic', 'Troop'),
(83, 'Bowler', 5, 'Epic', 'Troop'),
(84, 'Executioner', 5, 'Epic', 'Troop'),
(85, 'Cannon Cart', 5, 'Epic', 'Troop'),
(86, 'Giant Skeleton', 6, 'Epic', 'Troop'),
(87, 'Lightning', 6, 'Epic', 'Spell'),
(88, 'Goblin Giant', 6, 'Epic', 'Troop'),
(89, 'X-bow', 6, 'Epic', 'Building'),
(90, 'PEKKA', 7, 'Epic', 'Troop'),
(91, 'Electro Giant', 7, 'Epic', 'Troop'),
(92, 'Golem', 8, 'Epic', 'Troop')
ON CONFLICT (name) DO NOTHING;

--* Legendary Cards (21 entries)
INSERT INTO Card (card_id, name, elixir_cost, rarity, type) VALUES
(93, 'The Log', 2, 'Legendary', 'Spell'),
(94, 'Princess', 3, 'Legendary', 'Troop'),
(95, 'Miner', 3, 'Legendary', 'Troop'),
(96, 'Ice Wizard', 3, 'Legendary', 'Troop'),
(97, 'Royal Ghost', 3, 'Legendary', 'Troop'),
(98, 'Bandit', 3, 'Legendary', 'Troop'),
(99, 'Fisherman', 3, 'Legendary', 'Troop'),
(100, 'Inferno Dragon', 4, 'Legendary', 'Troop'),
(101, 'Electro Wizard', 4, 'Legendary', 'Troop'),
(102, 'Phoenix', 4, 'Legendary', 'Troop'),
(103, 'Magic Archer', 4, 'Legendary', 'Troop'),
(104, 'Lumberjack', 4, 'Legendary', 'Troop'),
(105, 'Night Witch', 4, 'Legendary', 'Troop'),
(106, 'Mother Witch', 4, 'Legendary', 'Troop'),
(107, 'Ram Rider', 5, 'Legendary', 'Troop'),
(108, 'Graveyard', 5, 'Legendary', 'Spell'),
(109, 'Goblin Machine', 5, 'Legendary', 'Troop'),
(110, 'Sparky', 6, 'Legendary', 'Troop'),
(111, 'Spirit Empress', 6, 'Legendary', 'Troop'),
(112, 'Mega Knight', 7, 'Legendary', 'Troop'),
(113, 'Lava Hound', 7, 'Legendary', 'Troop')
ON CONFLICT (name) DO NOTHING;


--* Champions (8 entries)
INSERT INTO Card (card_id, name, elixir_cost, rarity, type) VALUES
(114, 'Little Prince', 3, 'Champion', 'Troop'),
(115, 'Skeleton King', 4, 'Champion', 'Troop'),
(116, 'Golden Knight', 4, 'Champion', 'Troop'),
(117, 'Mighty Miner', 4, 'Champion', 'Troop'),
(118, 'Archer Queen', 5, 'Champion', 'Troop'),
(119, 'Monk', 5, 'Champion', 'Troop'),
(120, 'Goblinstein', 5, 'Champion', 'Troop'),
(121, 'Boss Bandit', 6, 'Champion', 'Troop')
ON CONFLICT (name) DO NOTHING;

--* Tower Troops (4 entries)
INSERT INTO Card (card_id, name, elixir_cost, rarity, type) VALUES
(122, 'Tower Princess', 0, 'Common', 'Tower Troop'),
(123, 'Cannoneer', 0, 'Epic', 'Tower Troop'),
(124, 'Dagger Duchess', 0, 'Legendary', 'Tower Troop'),
(125, 'Royal Chef', 0, 'Legendary', 'Tower Troop')
ON CONFLICT (name) DO NOTHING;



--! 2. Card Variants (The Children)
--* Normal Variants (125 entries)
INSERT INTO CardVariant (variant_id, name, variant_type, card_id) VALUES
(1, 'Skeletons', 'Normal', 1),
(2, 'Fire Spirit', 'Normal', 2),
(3, 'Electro Spirit', 'Normal', 3),
(4, 'Ice Spirit', 'Normal', 4),
(5, 'Goblins', 'Normal', 5),
(6, 'Spear Goblins', 'Normal', 6),
(7, 'Bomber', 'Normal', 7),
(8, 'Bats', 'Normal', 8),
(9, 'Berserker', 'Normal', 9),
(10, 'Snowball', 'Normal', 10),
(11, 'Zap', 'Normal', 11),
(12, 'Knight', 'Normal', 12),
(13, 'Archers', 'Normal', 13),
(14, 'Minions', 'Normal', 14),
(15, 'Arrows', 'Normal', 15),
(16, 'Cannon', 'Normal', 16),
(17, 'Goblin Gang', 'Normal', 17),
(18, 'Skeleton Barrel', 'Normal', 18),
(19, 'Firecracker', 'Normal', 19),
(20, 'Royal Delivery', 'Normal', 20),
(21, 'Skeleton Dragons', 'Normal', 21),
(22, 'Mortar', 'Normal', 22),
(23, 'Tesla', 'Normal', 23),
(24, 'Barbarians', 'Normal', 24),
(25, 'Minion Horde', 'Normal', 25),
(26, 'Rascals', 'Normal', 26),
(27, 'Royal Giant', 'Normal', 27),
(28, 'Elite Barbarians', 'Normal', 28),
(29, 'Royal Recruits', 'Normal', 29),
(30, 'Heal Spirit', 'Normal', 30),
(31, 'Ice Golem', 'Normal', 31),
(32, 'Suspicious Bush', 'Normal', 32),
(33, 'Tombstone', 'Normal', 33),
(34, 'Dart Goblin', 'Normal', 34),
(35, 'Earthquake', 'Normal', 35),
(36, 'Elixir Golem', 'Normal', 36),
(37, 'Mega Minion', 'Normal', 37),
(38, 'Musqueteer', 'Normal', 38),
(39, 'Mini PEKKA', 'Normal', 39),
(40, 'Goblin Hut', 'Normal', 40),
(41, 'Goblin Cage', 'Normal', 41),
(42, 'Fireball', 'Normal', 42),
(43, 'Valkyrie', 'Normal', 43),
(44, 'Battle Ram', 'Normal', 44),
(45, 'Bomb Tower', 'Normal', 45),
(46, 'Hog Rider', 'Normal', 46),
(47, 'Flying Machine', 'Normal', 47),
(48, 'Battle Healer', 'Normal', 48),
(49, 'Zappies', 'Normal', 49),
(50, 'Furnace','Normal' ,50),
(51, 'Goblin Demolisher', 'Normal', 51),
(52, 'Giant', 'Normal', 52),
(53, 'Wizard', 'Normal', 53),
(54, 'Inferno Tower', 'Normal', 54),
(55, 'Royal Hogs', 'Normal', 55),
(56, 'Rocket', 'Normal', 56),
(57, 'Barbarian Hut', 'Normal', 57),
(58, 'Elixir Collector', 'Normal', 58),
(59, 'Three Musketeers', 'Normal', 59),
(60, 'Mirror', 'Normal', 60),
(61, 'Barbarian Barrel', 'Normal', 61),
(62, 'Wall Breakers', 'Normal', 62),
(63, 'Goblin Curse', 'Normal', 63),
(64, 'Rage', 'Normal', 64),
(65, 'Skeleton Army', 'Normal', 65),
(66, 'Guards', 'Normal', 66),
(67, 'Goblin Barrel', 'Normal', 67),
(68, 'Vines', 'Normal', 68),
(69, 'Tornado', 'Normal', 69),
(70, 'Clone', 'Normal', 70),
(71, 'Void', 'Normal', 71),
(72, 'Baby Dragon', 'Normal', 72),
(73, 'Dark Prince', 'Normal', 73),
(74, 'Freeze', 'Normal', 74),
(75, 'Rune Giant', 'Normal', 75),
(76, 'Poison', 'Normal', 76),
(77, 'Hunter', 'Normal', 77),
(78, 'Goblin Drill', 'Normal', 78),
(79, 'Witch', 'Normal', 79),
(80, 'Balloon', 'Normal', 80),
(81, 'Prince', 'Normal', 81),
(82, 'Electro Dragon','Normal' ,82),
(83, 'Bowler','Normal' ,83),
(84, 'Executioner','Normal' ,84),
(85, 'Cannon Cart','Normal' ,85),
(86, 'Giant Skeleton','Normal' ,86),
(87, 'Lightning','Normal' ,87),
(88, 'Goblin Giant','Normal' ,88),
(89, 'X-bow','Normal' ,89),
(90, 'PEKKA','Normal' ,90),
(91, 'Electro Giant','Normal' ,91),
(92, 'Golem','Normal' ,92),
(93, 'The Log','Normal' ,93),
(94, 'Princess','Normal' ,94),
(95, 'Miner','Normal' ,95),
(96, 'Ice Wizard','Normal' ,96),
(97, 'Royal Ghost','Normal' ,97),
(98, 'Bandit','Normal' ,98),
(99, 'Fisherman','Normal' ,99),
(100, 'Inferno Dragon','Normal' ,100),
(101, 'Electro Wizard','Normal' ,101),
(102, 'Phoenix','Normal' ,102),
(103, 'Magic Archer','Normal' ,103),
(104, 'Lumberjack','Normal' ,104),
(105, 'Night Witch','Normal' ,105),
(106, 'Mother Witch','Normal' ,106),
(107, 'Ram Rider','Normal' ,107),
(108, 'Graveyard','Normal' ,108),
(109, 'Goblin Machine','Normal' ,109),
(110, 'Sparky','Normal' ,110),
(111, 'Spirit Empress','Normal' ,111),
(112, 'Mega Knight','Normal' ,112),
(113, 'Lava Hound','Normal' ,113),
(114, 'Little Prince', 'Normal', 114),
(115, 'Skeleton King', 'Normal', 115),
(116, 'Golden Knight', 'Normal', 116),
(117, 'Mighty Miner', 'Normal', 117),
(118, 'Archer Queen', 'Normal', 118),
(119, 'Monk', 'Normal', 119),
(120, 'Goblinstein', 'Normal', 120),
(121, 'Boss Bandit', 'Normal', 121),
(122, 'Tower Princess', 'Normal', 122),
(123, 'Cannoneer', 'Normal', 123),
(124, 'Dagger Duchess', 'Normal', 124),
(125, 'Royal Chef', 'Normal', 125)
ON CONFLICT (name, card_id) DO NOTHING;

--* Evolution Variants (38 entries)
INSERT INTO CardVariant (variant_id, name, variant_type, card_id) VALUES
(126, 'Evo Skeletons', 'Evolution', 1),
(127, 'Evo Ice Spirit', 'Evolution', 4),
(128, 'Evo Bomber', 'Evolution', 7),
(129, 'Evo Bats', 'Evolution', 8),
(130, 'Evo Snowball', 'Evolution', 10),
(131, 'Evo Zap', 'Evolution', 11),
(132, 'Evo Knight', 'Evolution', 12),
(133, 'Evo Archers', 'Evolution', 13),
(134, 'Evo Cannon', 'Evolution', 16),
(135, 'Evo Skeleton Barrel', 'Evolution', 18),
(136, 'Evo Firecracker', 'Evolution', 19),
(137, 'Evo Mortar', 'Evolution', 22),
(138, 'Evo Tesla', 'Evolution', 23),
(139, 'Evo Barbarians', 'Evolution', 24),
(140, 'Evo Royal Giant', 'Evolution', 25),
(141, 'Evo Royal Recruits', 'Evolution', 26),
(142, 'Evo Dart Goblin', 'Evolution', 27),
(143, 'Evo Muketeer', 'Evolution', 28),
(144, 'Evo Goblin Cage', 'Evolution', 29),
(145, 'Evo Valkyrie', 'Evolution', 30),
(146, 'Evo Battle Ram', 'Evolution', 44),
(147, 'Evo Furnace', 'Evolution', 50),
(148, 'Evo Wizard', 'Evolution', 51),
(149, 'Evo Royal Hogs', 'Evolution', 57),
(150, 'Evo Wall Breakers', 'Evolution', 62),
(151, 'Evo Skeleton Army', 'Evolution', 65),
(152, 'Evo Goblin Barrel', 'Evolution', 67),
(153, 'Evo Baby Dragon', 'Evolution', 72),
(154, 'Evo Hunter', 'Evolution', 77),
(155, 'Evo Goblin Drill', 'Evolution', 78),
(156, 'Evo Witch', 'Evolution', 79),
(157, 'Evo Electro Dragon', 'Evolution', 82),
(158, 'Evo Executioner', 'Evolution', 84),
(159, 'Evo Goblin Giant', 'Evolution', 88),
(160, 'Evo PEKKA', 'Evolution', 90),
(161, 'Evo Royal Ghost', 'Evolution', 97),
(162, 'Evo Inferno Dragon', 'Evolution', 100),
(163, 'Evo Lumberjack', 'Evolution', 104),
(164, 'Evo Mega Knight', 'Evolution', 112)
ON CONFLICT (name, card_id) DO NOTHING;

--* Hero Variants (10 entries)
INSERT INTO CardVariant (variant_id, name, variant_type, card_id) VALUES
(165, 'Hero Goblins', 'Hero', 5),
(166, 'Hero Knight', 'Hero', 12),
(167, 'Hero Ice Golem', 'Hero', 31),
(168, 'Hero Mega Minion', 'Hero', 37),
(169, 'Hero Musketeer', 'Hero', 38),
(170, 'Hero Mini PEKKA', 'Hero', 39),
(171, 'Hero Giant', 'Hero', 52),
(172, 'Hero Wizard', 'Hero', 53),
(173, 'Hero Barbarian Barrel', 'Hero', 61),
(174, 'Hero Magic Archer', 'Hero', 103)
ON CONFLICT (name, card_id) DO NOTHING;
